networks:
  tifa:
    external: true

services:
  tree:
    image: tree
    container_name: tree
    entrypoint: /app/entrypoint.sh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    hostname: ${HOSTNAME}
    labels:
      traefik.enable: true
      traefik.http.routers.tree.rule: Host(`${HOSTNAME}`)
      traefik.http.routers.tree.entrypoints: websecure
      traefik.http.routers.tree.tls.certresolver: letsencrypt
      traefik.http.services.tree.loadbalancer.server.port: 80
    networks:
      - tifa
    restart: always
    volumes:
      - ./backup/data:/var/www/html/data  # webtrees data files
      - ./backup/mysql:/backup/mysql  # webtrees mysql data
      - tifa_mysql:/var/lib/mysql

volumes:
  tifa_mysql:
    external: true
