---
networks:
  proxy:
    external: true

services:
  tree:
    image: tree
    container_name: tree
    entrypoint: /app/entrypoint.sh
    hostname: ${HOSTNAME:-}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tree.entrypoints=web"
      - "traefik.http.routers.tree.rule=Host(`${HOSTNAME:-}`)"
      - "traefik.http.routers.tree.service=tree"
      - "traefik.http.services.tree.loadbalancer.server.port=80"
    volumes:
      - ${DATA_DIR}/tree:/var/www/html/data
    networks:
      - proxy

  mysql:
    image: mysql:5.7.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TABLE_PREFIX: ${MYSQL_TABLE_PREFIX}
    restart: always
    hostname: ${HOSTNAME:-}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mysql.entrypoints=mysql"
      - "traefik.http.routers.mysql.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.mysql.service=mysql"
      - "traefik.http.services.mysql.loadbalancer.server.port=3306"
    volumes:
      - ${DATA_DIR}/db:/var/lib/mysql
    networks:
      - proxy
