networks:
  service:
    external: true

services:
  tree:
    image: tree
    container_name: tree
    entrypoint: /app/entrypoint.sh
    environment:
      HOSTNAME: ${HOSTNAME:?}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?}
      MYSQL_HOST: ${MYSQL_HOST:?}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
      MYSQL_PORT: ${MYSQL_PORT:?}
      MYSQL_USER: ${MYSQL_USER:?}
    labels:
      traefik.enable: true
      traefik.http.routers.tree.rule: Host(`${HOSTNAME:?}`)
      traefik.http.routers.tree.entrypoints: websecure
      traefik.http.routers.tree.tls.certresolver: letsencrypt
      traefik.http.services.tree.loadbalancer.server.port: 80
    networks:
      - service
    restart: always
    volumes:
      - ./backup/data:/var/www/html/data  # webtrees data files
